[tox]
envlist = py38,py39

[testenv]
deps = pytest
commands = pytest

[flake8]
max-line-length = 88
extend-ignore = E203
per-file-ignores =
  *.pyi: E301, E302, E305, E501, E701, E741, F401, F403, F405, F822