name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_9:
          python.version: "3.9"
        #Python3_10:
        #  python.version: "3.10"
        #Python3_11:
        #  python.version: "3.11"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          set -x  # Echo commands before they are run
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir pefile regex
          [ -f $(pwd)/tests/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/tests/requirements.txt
          sudo rm -rf /tmp/* ~/.cache/pip
        displayName: Setup Environment
      - script: |
          set -x  # Echo commands before they are run
          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          sudo env "PATH=$PATH" python -m pytest -p no:cacheprovider --durations=10 -rsx -xsvvv --disable-warnings
        displayName: Test
